baseURL = "https://rubencantareronavarro.github.io/covid19-routes/"
languageCode = "en-us"
title = "covid19-routes"
theme = "OneDly-Theme"
publishDir = "./public"

#
# Personalization params
#
[params]
    # project specific params
    description = "Guía para la realización de la encuesta"
    author_url = "https://directorio.uclm.es/persona.aspx?cod=VitMLWqxyigrTOHPtpDkNw=="
    author_name = "Rubén Cantarero Navarro"
    project_url = "https://arcoresearch.com/"

    # optionally specify where the content is
    # mainSections = ["post"] 

    # social share links to appear at the end
    socialShare          = true
    # Sets specific share to appear on posts (default behavior is to appear)
    socialShareTwitter   = true
    socialShareGoogleplus = false
    socialShareFacebook  = true
    socialShareReddit    = true
    socialShareLinkedin  = true
    socialShareStumbleupon = false
    socialSharePinterest = true
    socialShareEmail = true

    # theme's color scheme
    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

#
# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. Icons appear at the top of the page.
#
[social]
    # Coding Communities
    github           = "RubenCantareroNavarro"
    gitlab           = ""
    stackoverflow    = "" # User Number
    bitbucket        = ""
    jsfiddle         = ""
    codepen          = ""
    # Visual Art Communities
    deviantart       = ""
    flickr           = ""
    behance          = ""
    dribbble         = ""
    # Publishing Communities
    wordpress        = ""
    medium           = ""
    # Professional/Business Oriented Communities
    linkedin         = "rub%C3%A9n-cantarero-navarro-31695436/"
    linkedin_company = ""
    foursquare       = ""
    xing             = ""
    slideshare       = ""
    # Social Networks
    facebook         = ""
    googleplus       = ""
    reddit           = ""
    quora            = ""
    youtube          = ""
    vimeo            = ""
    whatsapp         = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat         = ""
    qq             = "" # User ID Number
    instagram        = ""
    tumblr           = ""
    twitter          = "rubencn90"
    skype            = ""
    snapchat         = ""
    pinterest        = ""
    telegram         = ""
    vine             = ""
    googlescholar    = ""
    orcid            = ""
    researchgate     = ""
    # Email
    email = "Ruben.Cantarero@uclm.es"

#
# Adjust privacy settings
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[privacy]
    [privacy.disqus]
      disable = true

    [privacy.googleAnalytics]
      disable = true
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true

    [privacy.instagram]
      disable = false
      simple = true

    [privacy.twitter]
      disable = false
      enableDNT = true
      simple = true

    [privacy.vimeo]
      disable = true
      simple = true

    [privacy.youtube]
      disable = false
      privacyEnhanced = true

#
# In simple mode for Instagram and a site styled with Bootstrap 4, 
# you may want to disable the inlines styles provided by Hugo:
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

