(load "/usr/share/scone/scone-start.lisp")
(load "scone-knowledge.d/00-relations-extension.lisp")
(load "scone-knowledge.d/01-general.lisp")
(load "scone-knowledge.d/03-covid19.lisp")
(load "scone-knowledge.d/02-schedules.lisp")
